format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$conda\
$character"""

[username]
format = '[$user](bold 045) '

[hostname]
format = '[$hostname](bold 045) '

[directory]
format = '[$path](bold 045)[$read_only](bold 196)'
read_only = ' (read only)'

[git_branch]
format = " [$branch](229)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)( $ahead_behind$stashed)](bold 229)"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "+"

[cmd_duration]
format = " [$duration](229)"

[conda]
format = "[$environment](250) "

[character]
success_symbol = "[❯](218)"
error_symbol = "[❯](218)"

